resources:
  - configmap.yaml
  - secret.yaml
  - postgres-pvc.yaml
  - postgres-service.yaml
  - postgres-deployment.yaml
  - initdb-configmap.yaml
  - conevent-service.yaml
  - conevent-deployment.yaml