apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'conevent-api'
        static_configs:
          - targets: [ 'conevent:3000' ]
      - job_name: 'conevent-postgres'
        static_configs:
          - targets: [ 'conevent-postgres:9187' ]