// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    name,
    ini_date,
    end_date,
    ini_time,
    end_time,
    location,
    budget,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, name, ini_date, end_date, ini_time, end_time, location, budget, status, created_at
`

type CreateEventParams struct {
	Name     string         `json:"name"`
	IniDate  pgtype.Date    `json:"ini_date"`
	EndDate  pgtype.Date    `json:"end_date"`
	IniTime  pgtype.Time    `json:"ini_time"`
	EndTime  pgtype.Time    `json:"end_time"`
	Location string         `json:"location"`
	Budget   pgtype.Numeric `json:"budget"`
	Status   string         `json:"status"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.Name,
		arg.IniDate,
		arg.EndDate,
		arg.IniTime,
		arg.EndTime,
		arg.Location,
		arg.Budget,
		arg.Status,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IniDate,
		&i.EndDate,
		&i.IniTime,
		&i.EndTime,
		&i.Location,
		&i.Budget,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events
WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEvent, id)
	return err
}

const getEvent = `-- name: GetEvent :one
SELECT id, name, ini_date, end_date, ini_time, end_time, location, budget, status, created_at FROM events
WHERE id = $1
`

func (q *Queries) GetEvent(ctx context.Context, id pgtype.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IniDate,
		&i.EndDate,
		&i.IniTime,
		&i.EndTime,
		&i.Location,
		&i.Budget,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT id, name, ini_date, end_date, ini_time, end_time, location, budget, status, created_at FROM events
ORDER BY created_at DESC
`

func (q *Queries) ListEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IniDate,
			&i.EndDate,
			&i.IniTime,
			&i.EndTime,
			&i.Location,
			&i.Budget,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET name = $2,
    ini_date = $3,
    end_date = $4,
    ini_time = $5,
    end_time = $6,
    location = $7,
    budget = $8,
    status = $9
WHERE id = $1
RETURNING id, name, ini_date, end_date, ini_time, end_time, location, budget, status, created_at
`

type UpdateEventParams struct {
	ID       pgtype.UUID    `json:"id"`
	Name     string         `json:"name"`
	IniDate  pgtype.Date    `json:"ini_date"`
	EndDate  pgtype.Date    `json:"end_date"`
	IniTime  pgtype.Time    `json:"ini_time"`
	EndTime  pgtype.Time    `json:"end_time"`
	Location string         `json:"location"`
	Budget   pgtype.Numeric `json:"budget"`
	Status   string         `json:"status"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.ID,
		arg.Name,
		arg.IniDate,
		arg.EndDate,
		arg.IniTime,
		arg.EndTime,
		arg.Location,
		arg.Budget,
		arg.Status,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IniDate,
		&i.EndDate,
		&i.IniTime,
		&i.EndTime,
		&i.Location,
		&i.Budget,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
