// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BudgetItem struct {
	ID         pgtype.UUID `json:"id"`
	EventID    pgtype.UUID `json:"event_id"`
	Name       string      `json:"name"`
	HasAWinner pgtype.Bool `json:"has_a_winner"`
}

type Event struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	IniDate   pgtype.Date        `json:"ini_date"`
	EndDate   pgtype.Date        `json:"end_date"`
	IniTime   pgtype.Time        `json:"ini_time"`
	EndTime   pgtype.Time        `json:"end_time"`
	Location  string             `json:"location"`
	Budget    pgtype.Numeric     `json:"budget"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Guest struct {
	ID      pgtype.UUID `json:"id"`
	EventID pgtype.UUID `json:"event_id"`
	Name    string      `json:"name"`
	Email   pgtype.Text `json:"email"`
	Phone   pgtype.Text `json:"phone"`
	Status  string      `json:"status"`
}

type Supplier struct {
	ID      pgtype.UUID    `json:"id"`
	Company string         `json:"company"`
	Price   pgtype.Numeric `json:"price"`
	Contact string         `json:"contact"`
	Status  string         `json:"status"`
	Winner  pgtype.Bool    `json:"winner"`
}
